### PR TITLE
Fix bug #196 && prepare v8.0.0 release

### LINKED ISSUE #196: Error on main
The env can be nil or an empty string introduced in https://github.com/heroku/hatchet/commit/a9d3dc55e7418fcc6e0cc77cb8261597b5e50bd8

```
     NoMethodError:
       undefined method `empty?' for nil:NilClass

           return ENV['GITHUB_HEAD_REF'] if !ENV['GITHUB_HEAD_REF'].empty?
                                                                   ^^^^^^^
```

We can fix with the lonely operator.

### PR DESCRIPTION
**Pull request by schneems**
The call to `empty?` will fail if the key GITHUB_HEAD_REF does not exist.

Before fixing this problem, I extracted the logic to its own testable class. Then I added tests, which also showed that `GITHUB_REF_NAME` would never be returned either (a previously unknown bug) because `!@env["GITHUB_HEAD_REF"]&.empty?` will always be truthy unless the key exists and it's empty.

This would (possibly) be cleaner with pattern matching. Ruby has pattern matching but we can't use it yet due to minimum supported Ruby version https://docs.ruby-lang.org/en/3.0/syntax/pattern_matching_rdoc.html.

Close #196

### CODE REVIEW

**Comment by schneems** [comment]
No changelog since that commit that introduced #196 has yet to be released.

**Review by edmorley — APPROVED** [review]
