### ISSUE TITLE
Error on main

### ISSUE THREAD

**Issue by schneems** [heroku/hatchet#196]
The env can be nil or an empty string introduced in https://github.com/heroku/hatchet/commit/a9d3dc55e7418fcc6e0cc77cb8261597b5e50bd8

```
     NoMethodError:
       undefined method `empty?' for nil:NilClass

           return ENV['GITHUB_HEAD_REF'] if !ENV['GITHUB_HEAD_REF'].empty?
                                                                   ^^^^^^^
```

We can fix with the lonely operator.
